# Generated by Django 6.0.5 on 2026-05-17 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drive', '0004_remove_extraction_file_delete_foldersummary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_path', models.CharField(max_length=2048, unique=True)),
                ('summary', models.TextField()),
                ('file_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Extraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('char_count', models.IntegerField(default=0)),
                ('truncated', models.BooleanField(default=False)),
                ('source_modified_time', models.DateTimeField(blank=True, null=True)),
                ('extracted_at', models.DateTimeField(auto_now=True)),
                ('error', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('summarized_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction', to='drive.pickedfile')),
            ],
        ),
    ]
