# Generated by Django 6.0.5 on 2026-05-17 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_foldersummary_alter_pickedfile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraction',
            name='file',
        ),
        migrations.DeleteModel(
            name='FolderSummary',
        ),
        migrations.DeleteModel(
            name='Extraction',
        ),
    ]
